 drop sequence if exists hibernate_sequence;
 create sequence hibernate_sequence start 4 increment 1;



 create table abit_spec (abit_id int8 not null, spec_id int8 not null, primary key (abit_id, spec_id));
 create table abiturient_subjs (abiturient_id_abit_code int8 not null, subject int4, subject_mark int4);
 create table abiturients (id_abit_code int8 not null, avg_diploma_mark float8, email varchar(50), password varchar(120), po_batkovi varchar(255), request_counter int4, surname varchar(255), username varchar(255), primary key (id_abit_code));
 create table abiturients_faculties (abiturient_id_abit_code int8 not null, faculties_faculty_idl int8 not null);
 create table faculty (faculty_idl int8 generated by default as identity, faculty_name varchar(255), primary key (faculty_idl));
 create table faculty_abiturients (faculty_faculty_idl int8 not null, abiturients_id_abit_code int8 not null, primary key (faculty_faculty_idl, abiturients_id_abit_code));
 create table faculty_specializations (faculty_faculty_idl int8 not null, specializations_id int8 not null, primary key (faculty_faculty_idl, specializations_id));
 create table roles (id int4 generated by default as identity, name varchar(20), primary key (id));
 create table specialization (id int8 generated by default as identity, specialization_code int2, specialization_name varchar(255), primary key (id));
 create table specialization_need_subjects (specialization_id int8 not null, subjects varchar(255) not null, primary key (specialization_id, subjects));
 create table user_roles (user_id int8 not null, role_id int4 not null, primary key (user_id, role_id));


/*
CREATE TABLE abiturients (
  id_abit_code int8 generated by default as identity,
  avg_diploma_mark float8,
  email varchar(50),
  password varchar(120),
  po_batkovi varchar(255),
  request_counter int4,
  surname varchar(255),
  username varchar(255),
  primary key (id_abit_code)
  );

  create table abiturients
  (
  id_abit_code int8 not null,
   avg_diploma_mark float8,
   email varchar(50),
   password varchar(120),
   po_batkovi varchar(255),
   request_counter int4,
   surname varchar(255),
   username varchar(255),
   primary key (id_abit_code)
   );

 CREATE TABLE faculty (
 faculty_idl int8 generated by default as identity,
   faculty_name varchar(255),
   primary key (faculty_idl)
   );

 CREATE TABLE abiturients_faculties (
 abiturient_id_abit_code int8 not null,
  faculties_faculty_idl int8 not null
  );

 CREATE TABLE roles (
 id int4 generated by default as identity,
  name varchar(20),
   primary key (id)
   );


 CREATE TABLE faculty_specializations (
  faculty_faculty_idl int8 not null,
  specializations_id int8 not null,
  primary key (faculty_faculty_idl,
  specializations_id)
  );

 CREATE TABLE map_test (
  id int8 not null,
  primary key (id)
  );

 CREATE table map_test_subjs (
  map_test_id int8 not null,
  subject int4,
  subject_mark int4);

 CREATE TABLE specialization
 (
     id int8 generated by default as identity,
     specialization_code int2,
     specialization_name varchar(255),
     primary key (id)
 );

 CREATE TABLE user_roles (
      user_id int8 not null,
      role_id int4 not null,
      primary key (user_id, role_id)
);

CREATE TABLE abiturient_subjs
(
    abiturient_id_abit_code bigint not null
            references abiturients,
    subject                 integer,
    subject_mark            integer
);

CREATE TABLE specialization_need_subjects
(
   specialization_id int8 not null,
   subjects varchar(255) not null,
   primary key (specialization_id, subjects)
);


create table abit_spec (abit_id int8 not null, spec_id int8 not null, primary key (abit_id, spec_id));

create table abit_spec
(
    abit_id bigint  not null,
    spec_id bigint  not null,
        primary key (abit_id, spec_id)
);
*/