INSERT INTO roles VALUES(1,'ROLE_USER');
INSERT INTO roles VALUES(2,'ROLE_MODERATOR');
INSERT INTO roles VALUES(3,'ROLE_ADMIN');

INSERT INTO user_roles VALUES(1,1);
INSERT INTO user_roles VALUES(1,2);
INSERT INTO user_roles VALUES(1,3);
